Search bar
WildCodeSchool/lyon-js-sept21-p2-g2-front pull request #18
Opened 2021-11-03 11:30 UTC by lea-weibel

2021-11-03 13:16 UTC, NycoChavanoud approved these changes

2021-11-04 13:08 UTC, ComicScrip requested changes

2021-11-04 13:08 UTC, ComicScrip commented on src/components/routes/Home.jsx
> +      const stuff = currentSearch.replace(currentSearch[0], capitalized);
stuff ?

2021-11-04 13:08 UTC, ComicScrip commented on src/components/routes/Home.jsx
> +      const truc = currentSearch[0].toUpperCase();
![image](https://user-images.githubusercontent.com/16140010/140318700-d938c76d-fad8-4535-bff7-bca55607d17a.png)

2021-11-04 13:08 UTC, ComicScrip commented on src/components/routes/Home.jsx
> +          .filter((country) => country.name.includes(search))
aucun pays n'apparait sans recherche

2021-11-04 13:10 UTC, ComicScrip commented
Essayez si possible de faire une recherche depuis l'API directement et pas prendre toute la liste pour filtrer côté client. Si l'API ne le permet pas, pas très grave.

2021-11-05 14:25 UTC, NycoChavanoud approved these changes

2021-11-05 14:36 UTC, merged