Express api - fixed link pbm
WildCodeSchool/lyon-js-sept21-p2-g2-front pull request #36
Opened 2021-11-10 15:03 UTC by NycoChavanoud

2021-11-10 15:04 UTC, JoLrt-dev approved these changes

2021-11-10 15:05 UTC, William-Louis-Louisy approved these changes

2021-11-11 11:47 UTC, ComicScrip requested changes

2021-11-11 11:47 UTC, ComicScrip commented on src/components/AbstractBlogPost.jsx
> +      .get(`http://localhost:5000/destinations/${name}/blog-posts`)
debut d'url à mettre dans un .env

2021-11-11 11:47 UTC, ComicScrip commented on src/components/PostsContext.js
> +import React, { createContext, useState } from 'react';
Pourquoi ce context ?

2021-11-11 11:47 UTC, ComicScrip commented on src/components/routes/PostDetails.jsx
> +      .get(`http://localhost:5000/posts/${id}`)
=> .env

2021-11-14 22:37 UTC, William-Louis-Louisy approved these changes

2021-11-16 08:21 UTC, merged